"""
Constantes do módulo SLA.
"""

# Status de chamado
STATUS_ABERTO = "Aberto"
STATUS_EM_ATENDIMENTO = "Em atendimento"
STATUS_AGUARDANDO = "Aguardando"
STATUS_CONCLUIDO = "Concluído"
STATUS_CANCELADO = "Cancelado"

STATUSES_ATIVOS = [STATUS_ABERTO, STATUS_EM_ATENDIMENTO]
STATUSES_PAUSADOS = [STATUS_AGUARDANDO]
STATUSES_FINAIS = [STATUS_CONCLUIDO, STATUS_CANCELADO]

# Prioridades padrão
PRIORIDADE_CRITICA = "Crítica"
PRIORIDADE_ALTA = "Alta"
PRIORIDADE_NORMAL = "Normal"
PRIORIDADE_BAIXA = "Baixa"

PRIORIDADES = [PRIORIDADE_CRITICA, PRIORIDADE_ALTA, PRIORIDADE_NORMAL, PRIORIDADE_BAIXA]

# Ações de SLA
ACAO_INICIAR = "iniciar_sla"
ACAO_PRIMEIRA_RESPOSTA = "primeira_resposta"
ACAO_PAUSA = "pausa"
ACAO_RETOMA = "retoma"
ACAO_CONCLUIDO = "concluido"
ACAO_ESCALONAMENTO = "escalonamento"

# Status SLA
STATUS_SLA_DENTRO = "dentro"
STATUS_SLA_FORA = "fora"

# Tipos de feriado
TIPO_FERIADO_FIXO = "fixo"
TIPO_FERIADO_MOVEL = "movel"
TIPO_FERIADO_PONTUAL = "pontual"

TIPOS_FERIADO = [TIPO_FERIADO_FIXO, TIPO_FERIADO_MOVEL, TIPO_FERIADO_PONTUAL]

# Configurações padrão de SLA (horas)
SLA_RESPOSTA_CRITICA = 1
SLA_RESPOSTA_ALTA = 2
SLA_RESPOSTA_NORMAL = 4
SLA_RESPOSTA_BAIXA = 8

SLA_RESOLUCAO_CRITICA = 4
SLA_RESOLUCAO_ALTA = 8
SLA_RESOLUCAO_NORMAL = 24
SLA_RESOLUCAO_BAIXA = 48

# Percentual padrão de risco (75%)
PERCENTUAL_RISCO_PADRAO = 75.0

# Horário comercial padrão
HORA_INICIO_PADRAO = "08:00"
HORA_FIM_PADRAO = "18:00"
TIMEZONE_PADRAO = "America/Sao_Paulo"

# Cache
CACHE_TTL_METRICAS = 30  # minutos
CACHE_TTL_INDICADORES = 5  # minutos
